/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://zas7imcwqvhdngp7chdt5tissa.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qbyq2yyfcnbslbzne7vaomw34q",
    "aws_cognito_identity_pool_id": "eu-north-1:937adf05-04b0-435d-ae13-2e023064433b",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_GzC4CfvAy",
    "aws_user_pools_web_client_id": "4cpoonufllint4852507j92jos",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "doplay-20240705201240-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-north-1",
    "aws_content_delivery_url": "https://d2f89gpdxj4pe0.cloudfront.net"
};


export default awsmobile;
